In [38]:
import numpy as np
import matplotlib.pyplot as plt
import glob
import sys
import pickle
import csv
import random

In [25]:
#drug_iddict        final_Virus_DTI_add_organism.tsv  human_seq_dict.pkl    VDTI_net.npy           virusseq_add_ncov.pkl
#drug_info.tsv      HDTI_net.npy                      human_seq_iddict.pkl  VHI_net.npy            virusseq_add_ncovseqdict.pkl
#Drug_simi_net.npy  human.npy                         PPI_net.npy           virusseq_add_ncov.npy

In [26]:
#NPY
drug_simi_net = np.load("DTI-data/Drug_simi_net.npy")
print(drug_simi_net.shape)
print(drug_simi_net[0])
HDTI_net = np.load("DTI-data/HDTI_net.npy")
print(HDTI_net.shape)
print(HDTI_net[0])
human = np.load("DTI-data/human.npy")
print(human.shape)
print(human[0])
ppi_net = np.load("DTI-data/PPI_net.npy")
print(ppi_net.shape)
print(ppi_net[0])
#This is our ultimate target
vdti_net = np.load("DTI-data/VDTI_net.npy")
print("!", vdti_net.shape)
print("!", vdti_net[0])
vhi_net = np.load("DTI-data/VHI_net.npy")
print(vhi_net.shape)
print(vhi_net[0])
virusseq_add_ncov = np.load("DTI-data/virusseq_add_ncov.npy")
print(virusseq_add_ncov.shape)
print(virusseq_add_ncov[0])

(6255, 6255)
[1.         0.12962963 0.09183674 ... 0.1        0.11504425 0.16842106]
(6255, 2567)
[0. 0. 0. ... 0. 0. 0.]
(2567, 2567)
[1.         0.13113017 0.12197821 ... 0.10474334 0.05903945 0.08940052]
(2567, 2567)
[1. 0. 0. ... 0. 0. 0.]
! (6255, 404)
! [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 

In [27]:
#PICKLE
with open("DTI-data/human_seq_dict.pkl", 'rb') as f:
    human_seq_dict = pickle.load(f)
with open("DTI-data/human_seq_iddict.pkl", 'rb') as f:    
    human_seq_iddict = pickle.load(f)
with open("DTI-data/virusseq_add_ncov.pkl", 'rb') as f:
    virusseq_add_ncov = pickle.load(f)
with open("DTI-data/virusseq_add_ncovseqdict.pkl", 'rb') as f:
    virusseq_add_ncovseqdict = pickle.load(f)
with open("DTI-data/drug_iddict", 'rb') as f:
    drug_iddict = pickle.load(f)

print(human_seq_dict[list(human_seq_dict.keys())[0]][:100], "\n")
print(human_seq_iddict[list(human_seq_iddict.keys())[0]], "\n")
print(virusseq_add_ncov[list(virusseq_add_ncov.keys())[0]], "\n")
print(virusseq_add_ncovseqdict[list(virusseq_add_ncovseqdict.keys())[0]][:100], "\n")
print(drug_iddict[list(drug_iddict.keys())[0]], "\n")

MQIELSTCFFLCLLRFCFSATRRYYLGAVELSWDYMQSDLGELPVDARFPPRVPKSFPFNTSVVYKKTLFVEFTDHLFNIAKPRPPWMGLLGPTIQAEVY 

1 

0 

MGARASVLSGGELDKWEKIRLRPGGKKQYKLKHIVWASRELERFAVNPGLLETSEGCRQILGQLQPSLQTGSEELRSLYNTIAVLYCVHQRIDVKDTKEA 

0 



In [28]:
#TSV
with open("DTI-data/drug_info.tsv", "r") as f:
    drug_info = csv.reader(f, delimiter = '\t')
    drug_info = list(drug_info)
with open("DTI-data/final_Virus_DTI_add_organism.tsv", "r") as f:
    final_Virus_DTI_add_organism = csv.reader(f, delimiter = '\t') 
    final_Virus_DTI_add_organism = list(final_Virus_DTI_add_organism)

print(drug_info[0:2])
print("")
print(final_Virus_DTI_add_organism[0:2])

[['InChI', 'DrugBank ID', 'Drug name'], ['InChI=1S/C19H25N8O9P/c20-13-1-2-26(19(30)25-13)15-4-10(11(5-28)34-15)36-37(31,32)33-6-12-9(29)3-14(35-12)27-8-24-16-17(21)22-7-23-18(16)27/h1-2,7-12,14-15,28-29H,3-6H2,(H,31,32)(H2,20,25,30)(H2,21,22,23)/t9-,10-,11+,12+,14+,15+/m0/s1', 'DB02573', "2'-deoxycytidine-2'-deoxyadenosine-3',5'-monophosphate"]]

[['InChI', 'Smiles', 'sequence', 'uniprotid', 'origanism'], ['InChI=1S/C31H51N5O5/c1-20(2)28(32-22(5)37)30(40)34-26(17-24-13-9-7-10-14-24)27(39)19-36(18-25-15-11-8-12-16-25)35-31(41)29(21(3)4)33-23(6)38/h7,9-10,13-14,20-21,25-29,39H,8,11-12,15-19H2,1-6H3,(H,32,37)(H,33,38)(H,34,40)(H,35,41)/t26-,27-,28-,29-/m0/s1', 'CC(O)=N[C@H](C(O)=N[C@@H](Cc1ccccc1)[C@@H](O)CN(CC1CCCCC1)N=C(O)[C@@H](N=C(C)O)C(C)C)C(C)C', 'PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKMIGGIGGFIKVRQYDQILIEICGHKAIGTVLVGPTPVNIIGRNLLTQIGCTLNF', 'Q999P5', 'Human immunodeficiency virus 1']]


In [29]:
!ls

data.ipynb   DTI-data		     KnowledgeGraphEmbedding
data_.ipynb  homework_repositioning


In [66]:
# KnowledgeGraphEmbedding expects 5 files

# entities.dict - maps entities to ids
# relations.dict - maps relations to ids
# train.txt - entity id to relation id
# valid.txt - can be blank
# test.txt

print(HDTI_net.shape)
print(HDTI_net[0])

print("!", vdti_net.shape)
print("!", vdti_net[0])

print(vhi_net.shape)
print(vhi_net[0])

#entities.dict

DRUG_COUNT = 6255
HUMAN_COUNT = 2567
VIRUS_COUNT = 404

sum_ = DRUG_COUNT + HUMAN_COUNT + VIRUS_COUNT

HUMAN_OFFSET = 6255
VIRUS_OFFSET = 6255 + 2567

with open("KnowledgeGraphEmbedding/data/C-19/entities.dict", "w") as f:
    cnt = 0
    for i in range(DRUG_COUNT + HUMAN_COUNT + VIRUS_COUNT):
        f.write(str(i) + "\t" + str(i) + "\n")
        cnt += 1
    print(cnt)
    print(sum_)
    assert(cnt == sum_)

#relations.dict

with open("KnowledgeGraphEmbedding/data/C-19/relations.dict", "w") as f:
    f.write("0\t0\n")
    f.write("1\t1\n")
    f.write("2\t2")
#with open("KnowledgeGraphEmbedding/data/C-19/entities.dict" as f):

#all.txt

with open("KnowledgeGraphEmbedding/data/C-19/all.dict", "w") as f:
    #drug -> human
    i = 0 
    for _, r in np.ndenumerate(HDTI_net):
        j = 0
        for _, v in np.ndenumerate(r):
            assert(j + HUMAN_OFFSET < sum_)
            if v:
                f.write(str(i) + "\t" + "0"  + "\t" + str(j + HUMAN_OFFSET) + "\n")
            j += 1
        j = 0
        i += 1
    #drug -> virus
    i = 0
    for _, r in np.ndenumerate(vdti_net):
        j = 0
        for _, v in np.ndenumerate(r):
            #print(v.shape)
            assert(j + VIRUS_OFFSET < sum_)
            if v:
                f.write(str(i) + "\t" + "1"  + "\t" +  str(j + VIRUS_OFFSET) + "\n")  
            j += 1
        i += 1     
    #virus -> human
    i = 0
    for _, r in np.ndenumerate(vhi_net):
        j = 0
        for _, v in np.ndenumerate(r):
            assert(i + VIRUS_OFFSET < sum_ and j + HUMAN_OFFSET < sum_)
            if v:
                f.write(str(i + VIRUS_OFFSET) + "\t" + "2"  + "\t" + str(j + HUMAN_OFFSET) + "\n")        
            j += 1
        i += 1     

TRAIN_TEST_SPLIT = 0.85
TRAIN_VAL_SPLIT  = 0.90

with open("KnowledgeGraphEmbedding/data/C-19/all.dict", "r") as f:
    lst = f.readlines()
    train_t = random.sample(lst, int(len(lst) * TRAIN_TEST_SPLIT))
    train   = random.sample(train_t, int(len(train_t) * TRAIN_VAL_SPLIT))
    val     = [e for e in train_t if e not in train]
    test    = [e for e in lst if e not in train_t]
    #train.txt
    with open("KnowledgeGraphEmbedding/data/C-19/train.txt", "w+") as f:
        f.writelines(train)
    #valid.txt
    with open("KnowledgeGraphEmbedding/data/C-19/val.txt", "w+")   as f:
        f.writelines(val)
    #test.txt
    with open("KnowledgeGraphEmbedding/data/C-19/test.txt", "w+")  as f:
        f.writelines(test)

(6255, 2567)
[0. 0. 0. ... 0. 0. 0.]
! (6255, 404)
! [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

AssertionError: 

In [68]:
#train, test

!CUDA_VISIBLE_DEVICES=0 python -u KnowledgeGraphEmbedding/codes/run.py --do_train \
 --cuda \
 --do_valid \
 --do_test \
 --data_path KnowledgeGraphEmbedding/data/C-19 \
 --model RotatE \
 -n 256 -b 1024 -d 1000 \
 -g 24.0 -a 1.0 -adv \
 -lr 0.0001 --max_steps 150000 \
 -save KnowledgeGraphEmbedding/models/RotatE_C-19_0 --test_batch_size 16 -de

2020-05-27 20:11:22,422 INFO     Model: RotatE
2020-05-27 20:11:22,422 INFO     Data Path: KnowledgeGraphEmbedding/data/C-19
2020-05-27 20:11:22,422 INFO     #entity: 9226
2020-05-27 20:11:22,422 INFO     #relation: 3
Traceback (most recent call last):
  File "KnowledgeGraphEmbedding/codes/run.py", line 361, in <module>
    main(parse_args())
  File "KnowledgeGraphEmbedding/codes/run.py", line 211, in main
    train_triples = read_triple(os.path.join(args.data_path, 'train.txt'), entity2id, relation2id)
  File "KnowledgeGraphEmbedding/codes/run.py", line 127, in read_triple
    triples.append((entity2id[h], relation2id[r], entity2id[t]))
KeyError: '10114'
